blank_issues_enabled: false
contact_links:
  - name: Known limitations
    url: https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request
    about: Please review before opening a new issue
